### ISSUE TITLE
YAML configuration files support

### ISSUE THREAD

**Issue by bySabi** [smittytone/PreviewCode#1]
Add support for YAML configuration files
Thanks

**Comment by smittytone** [comment]
That's the job of [PreviewYaml](https://apps.apple.com/us/app/previewyaml/id1564574724?ls=1).

**Comment by bySabi** [comment]
@smittytone I don't see the point of installing a separate app just for YAML files when `PreviewCode` supports other types of configuration files like: `.conf`, `.cf`, `.cfg`, `.ini`, `.rc` 

I guess it's because you need to monetize your work. It is not a criticism.

Still, thanks for making this App open source
