### ISSUE TITLE
Add complete support for .NET files

### ISSUE THREAD

**Issue by massimilianokraus-kappas** [smittytone/PreviewCode#10]
You should add support for these text files that are very used in every middle-to-big .NET project:
- .csproj (fundamental!)
- .sln (fundamental!)
- .nuspec
- .props
- .target
- .config

**Comment by smittytone** [comment]
I would need sample file content for any of these if I was to add support for them to PreviewCode.

**Comment by smittytone** [comment]
PS. Closing this thread and migrating it to the file-type request thread.
