### ISSUE TITLE
some cpp file can't be previewed

### ISSUE THREAD

**Issue by tangb4c** [smittytone/PreviewCode#3]
this is bad, 
<img width="804" alt="Screen Shot 2022-08-22 at 21 04 44" src="https://user-images.githubusercontent.com/5152043/185928443-ac266fd6-6fda-4382-86b3-76dccc3884eb.png">

other is ok, 
<img width="737" alt="Screen Shot 2022-08-22 at 21 05 12" src="https://user-images.githubusercontent.com/5152043/185928451-df5cef01-6aac-4a61-a6b6-3773c4b79071.png">

**Comment by smittytone** [comment]
That looks like Swift is unable to open the file as utf-8. What's your encoding? I'd need to see the contents (cleaned of confidential data) to debug further.

**Comment by tangb4c** [comment]
yes, the file contains some CJK charaters, and be encoded with cp936/gb231. 
I hope to support non-utf8 encoded file, thx.

[mmpaymchqcbehaviorupdatersvrtestimpl_pb.cpp.gz](https://github.com/smittytone/PreviewCode/files/9398610/mmpaymchqcbehaviorupdatersvrtestimpl_pb.cpp.gz)

**Comment by smittytone** [comment]
There we go. Update coming shortly.
![Screenshot 2022-08-24 at 09 22 47](https://user-images.githubusercontent.com/6843743/186368535-c211e81e-e638-4292-8c02-6173a0da2288.png)
y
