### ISSUE TITLE
Can you add .srt supportability?

### ISSUE THREAD

**Issue by gustavohellwig** [smittytone/PreviewCode#4]
Can you add .srt supportability?
Thank you !!!

**Comment by smittytone** [comment]
If you mean for subtitles, no. That's outside the scope of PreviewCode. But I have another app in the works that might help with those.

**Comment by gustavohellwig** [comment]
ok. Can I add it manually in some place of the app, so it can at least show as a normal text preview?
Can you add me as a beta tester of your new app? thank you.

**Comment by smittytone** [comment]
.srt is now available via [PreviewText](https://apps.apple.com/us/app/previewtext/id1660037028), which is free
