### ISSUE TITLE
Some extensions/files that could be added for the code preview.

### ISSUE THREAD

**Issue by oderwat** [smittytone/PreviewCode#5]
Hi, I just bought your extensions, and of course, I have a request :)

Could you please add those standard Go files to be previewed?

- go.mod
- go.sum
- go.work

And probably (which actually is YAML though):

- Dockerfile (yam)
- [Earthfile](https://earthly.dev/) (YAML / that would be great, as I use them a lot)

NOTE: I have no idea if it is possible to add those, especially the later ones.

**Comment by smittytone** [comment]
I can look into adding those. Dockerfiles are already on the roadmap.

**Comment by mrhammadasif** [comment]
Most common file extension for TypeScript is `.ts`. Also, need support for `.vue` extension

**Comment by smittytone** [comment]
As it says in the Read Me, PreviewCode doesn’t support TypeScript .ts files because the .ts file extension is a standard for transport stream video files. The workaround is to use .tsx for TypeScript files.

But I can look at adding `.vue` support. I take it you mean `.vue` for View.js?

**Comment by mrhammadasif** [comment]
> But I can look at adding `.vue` support. I take it you mean `.vue` for View.js?

Actually, it means Vue.js https://vuejs.org/. For reference, you can have a look at following packages:

- https://www.npmjs.com/package/vue-code-highlight
- https://github.com/vuejs/language-tools

**Comment by SoKamil** [comment]
> As it says in the Read Me, PreviewCode doesn’t support TypeScript .ts files because the .ts file extension is a standard for transport stream video files. The workaround is to use .tsx for TypeScript files.
> 
> But I can look at adding `.vue` support. I take it you mean `.vue` for View.js?

Can't this behavior for .ts be overridden?

**Comment by smittytone** [comment]
I’m considering doing that since I guess most folks using PreviewCode (including me) will be using `.ts` for TypeScript files rather that transport stream video files.

**Comment by oderwat** [comment]
Even if they have both, can't you open it and if it is not text, show a message, explaining what happened?

**Comment by smittytone** [comment]
Update: preliminary `.vue` support coming in the next release, along with `.gml` (GameMaker Language) and some Xcode-specific file types.

Support for the Go `.mod`, `.sum` and `.work` files will appear in the next release of PreviewText, which is free.

Actively researching solutions to the `.ts` issue, but a solution may not make it to the next release.
