### ISSUE TITLE
Need a setting for preferred theme as per time of day

### ISSUE THREAD

**Issue by arifmetic** [smittytone/PreviewCode#6]
As of right now, there seems to be only one global theme in the previewer preferences. But it would be greatly appreciated if there would be two theme options - one for dark and another for light- so it changes with time of the day for users who have set their macOS theme to be automatic, which switches from light to dark with reference to time.

Without it, the system looks inconsistent with certain files opening in light theme (how macOS handles the previews) and others (code) always opening with a dark theme.

Other than this, I'd just like to thank for the wonderful app that's open-source and on the app-store. Takes the pain away of inability of installing un-notarized apps or dealing with privacy policy of similar proprietary apps.

**Comment by smittytone** [comment]
I’m actively researching how to implement this. I’m hoping to add it in a future release.
