### ISSUE TITLE
typescript .ts files don't work

### ISSUE THREAD

**Issue by lyon007** [smittytone/PreviewCode#7]
.tsx and .typescript files work, only .ts does not

system：Ventura 13.4.1

<img width="391" alt="image" src="https://github.com/smittytone/PreviewCode/assets/21033119/393fcac6-71fc-4e38-9e48-33d047a1cd90">

**Comment by smittytone** [comment]
No. As it says in the Read Me, "PreviewCode will not render TypeScript .ts files. This is because the .ts file extension is pre-set on macOS to MPEG-2 transport stream video files." I'm investigating ways of overriding that, but for now, .ts is not (and can't be) supported.
